/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesVisiteCamerounRouteImport } from './routes/services.visite-cameroun'
import { Route as ServicesVisaSchengenRouteImport } from './routes/services.visa-schengen'
import { Route as ServicesLongSejoursRouteImport } from './routes/services.long-sejours'
import { Route as ServicesLogementRouteImport } from './routes/services.logement'
import { Route as ServicesCourtSejoursRouteImport } from './routes/services.court-sejours'
import { Route as ServicesCommunityManagementRouteImport } from './routes/services.community-management'
import { Route as ServicesCautionAviRouteImport } from './routes/services.caution-avi'
import { Route as ServicesBilletsAvionRouteImport } from './routes/services.billets-avion'
import { Route as ServicesAccueilIntegrationRouteImport } from './routes/services.accueil-integration'
import { Route as DestinationsCountryRouteImport } from './routes/destinations.$country'
import { Route as AuthenticatedNewRequestRouteImport } from './routes/_authenticated/new-request'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ServicesFormationsIndexRouteImport } from './routes/services.formations.index'
import { Route as AuthenticatedMyRequestsIndexRouteImport } from './routes/_authenticated/my-requests.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ServicesFormationsToeicRouteImport } from './routes/services.formations.toeic'
import { Route as ServicesFormationsTcfRouteImport } from './routes/services.formations.tcf'
import { Route as ServicesFormationsAllemandRouteImport } from './routes/services.formations.allemand'
import { Route as AuthenticatedMyRequestsIdRouteImport } from './routes/_authenticated/my-requests.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisiteCamerounRoute = ServicesVisiteCamerounRouteImport.update({
  id: '/services/visite-cameroun',
  path: '/services/visite-cameroun',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisaSchengenRoute = ServicesVisaSchengenRouteImport.update({
  id: '/services/visa-schengen',
  path: '/services/visa-schengen',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLongSejoursRoute = ServicesLongSejoursRouteImport.update({
  id: '/services/long-sejours',
  path: '/services/long-sejours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLogementRoute = ServicesLogementRouteImport.update({
  id: '/services/logement',
  path: '/services/logement',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCourtSejoursRoute = ServicesCourtSejoursRouteImport.update({
  id: '/services/court-sejours',
  path: '/services/court-sejours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCommunityManagementRoute =
  ServicesCommunityManagementRouteImport.update({
    id: '/services/community-management',
    path: '/services/community-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCautionAviRoute = ServicesCautionAviRouteImport.update({
  id: '/services/caution-avi',
  path: '/services/caution-avi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBilletsAvionRoute = ServicesBilletsAvionRouteImport.update({
  id: '/services/billets-avion',
  path: '/services/billets-avion',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAccueilIntegrationRoute =
  ServicesAccueilIntegrationRouteImport.update({
    id: '/services/accueil-integration',
    path: '/services/accueil-integration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationsCountryRoute = DestinationsCountryRouteImport.update({
  id: '/destinations/$country',
  path: '/destinations/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewRequestRoute = AuthenticatedNewRequestRouteImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicesFormationsIndexRoute = ServicesFormationsIndexRouteImport.update({
  id: '/services/formations/',
  path: '/services/formations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyRequestsIndexRoute =
  AuthenticatedMyRequestsIndexRouteImport.update({
    id: '/my-requests/',
    path: '/my-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicesFormationsToeicRoute = ServicesFormationsToeicRouteImport.update({
  id: '/services/formations/toeic',
  path: '/services/formations/toeic',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFormationsTcfRoute = ServicesFormationsTcfRouteImport.update({
  id: '/services/formations/tcf',
  path: '/services/formations/tcf',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFormationsAllemandRoute =
  ServicesFormationsAllemandRouteImport.update({
    id: '/services/formations/allemand',
    path: '/services/formations/allemand',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMyRequestsIdRoute =
  AuthenticatedMyRequestsIdRouteImport.update({
    id: '/my-requests/$id',
    path: '/my-requests/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/new-request': typeof AuthenticatedNewRequestRoute
  '/destinations/$country': typeof DestinationsCountryRoute
  '/services/accueil-integration': typeof ServicesAccueilIntegrationRoute
  '/services/billets-avion': typeof ServicesBilletsAvionRoute
  '/services/caution-avi': typeof ServicesCautionAviRoute
  '/services/community-management': typeof ServicesCommunityManagementRoute
  '/services/court-sejours': typeof ServicesCourtSejoursRoute
  '/services/logement': typeof ServicesLogementRoute
  '/services/long-sejours': typeof ServicesLongSejoursRoute
  '/services/visa-schengen': typeof ServicesVisaSchengenRoute
  '/services/visite-cameroun': typeof ServicesVisiteCamerounRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/my-requests/$id': typeof AuthenticatedMyRequestsIdRoute
  '/services/formations/allemand': typeof ServicesFormationsAllemandRoute
  '/services/formations/tcf': typeof ServicesFormationsTcfRoute
  '/services/formations/toeic': typeof ServicesFormationsToeicRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/my-requests/': typeof AuthenticatedMyRequestsIndexRoute
  '/services/formations/': typeof ServicesFormationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/new-request': typeof AuthenticatedNewRequestRoute
  '/destinations/$country': typeof DestinationsCountryRoute
  '/services/accueil-integration': typeof ServicesAccueilIntegrationRoute
  '/services/billets-avion': typeof ServicesBilletsAvionRoute
  '/services/caution-avi': typeof ServicesCautionAviRoute
  '/services/community-management': typeof ServicesCommunityManagementRoute
  '/services/court-sejours': typeof ServicesCourtSejoursRoute
  '/services/logement': typeof ServicesLogementRoute
  '/services/long-sejours': typeof ServicesLongSejoursRoute
  '/services/visa-schengen': typeof ServicesVisaSchengenRoute
  '/services/visite-cameroun': typeof ServicesVisiteCamerounRoute
  '/services': typeof ServicesIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/my-requests/$id': typeof AuthenticatedMyRequestsIdRoute
  '/services/formations/allemand': typeof ServicesFormationsAllemandRoute
  '/services/formations/tcf': typeof ServicesFormationsTcfRoute
  '/services/formations/toeic': typeof ServicesFormationsToeicRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/my-requests': typeof AuthenticatedMyRequestsIndexRoute
  '/services/formations': typeof ServicesFormationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/new-request': typeof AuthenticatedNewRequestRoute
  '/destinations/$country': typeof DestinationsCountryRoute
  '/services/accueil-integration': typeof ServicesAccueilIntegrationRoute
  '/services/billets-avion': typeof ServicesBilletsAvionRoute
  '/services/caution-avi': typeof ServicesCautionAviRoute
  '/services/community-management': typeof ServicesCommunityManagementRoute
  '/services/court-sejours': typeof ServicesCourtSejoursRoute
  '/services/logement': typeof ServicesLogementRoute
  '/services/long-sejours': typeof ServicesLongSejoursRoute
  '/services/visa-schengen': typeof ServicesVisaSchengenRoute
  '/services/visite-cameroun': typeof ServicesVisiteCamerounRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/my-requests/$id': typeof AuthenticatedMyRequestsIdRoute
  '/services/formations/allemand': typeof ServicesFormationsAllemandRoute
  '/services/formations/tcf': typeof ServicesFormationsTcfRoute
  '/services/formations/toeic': typeof ServicesFormationsToeicRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/my-requests/': typeof AuthenticatedMyRequestsIndexRoute
  '/services/formations/': typeof ServicesFormationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/request'
    | '/search'
    | '/account'
    | '/new-request'
    | '/destinations/$country'
    | '/services/accueil-integration'
    | '/services/billets-avion'
    | '/services/caution-avi'
    | '/services/community-management'
    | '/services/court-sejours'
    | '/services/logement'
    | '/services/long-sejours'
    | '/services/visa-schengen'
    | '/services/visite-cameroun'
    | '/services/'
    | '/admin/$id'
    | '/admin/users'
    | '/my-requests/$id'
    | '/services/formations/allemand'
    | '/services/formations/tcf'
    | '/services/formations/toeic'
    | '/admin/'
    | '/my-requests/'
    | '/services/formations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/request'
    | '/search'
    | '/account'
    | '/new-request'
    | '/destinations/$country'
    | '/services/accueil-integration'
    | '/services/billets-avion'
    | '/services/caution-avi'
    | '/services/community-management'
    | '/services/court-sejours'
    | '/services/logement'
    | '/services/long-sejours'
    | '/services/visa-schengen'
    | '/services/visite-cameroun'
    | '/services'
    | '/admin/$id'
    | '/admin/users'
    | '/my-requests/$id'
    | '/services/formations/allemand'
    | '/services/formations/tcf'
    | '/services/formations/toeic'
    | '/admin'
    | '/my-requests'
    | '/services/formations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/request'
    | '/search'
    | '/_authenticated/account'
    | '/_authenticated/new-request'
    | '/destinations/$country'
    | '/services/accueil-integration'
    | '/services/billets-avion'
    | '/services/caution-avi'
    | '/services/community-management'
    | '/services/court-sejours'
    | '/services/logement'
    | '/services/long-sejours'
    | '/services/visa-schengen'
    | '/services/visite-cameroun'
    | '/services/'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/users'
    | '/_authenticated/my-requests/$id'
    | '/services/formations/allemand'
    | '/services/formations/tcf'
    | '/services/formations/toeic'
    | '/_authenticated/admin/'
    | '/_authenticated/my-requests/'
    | '/services/formations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  RequestRoute: typeof RequestRoute
  SearchRoute: typeof SearchRoute
  DestinationsCountryRoute: typeof DestinationsCountryRoute
  ServicesAccueilIntegrationRoute: typeof ServicesAccueilIntegrationRoute
  ServicesBilletsAvionRoute: typeof ServicesBilletsAvionRoute
  ServicesCautionAviRoute: typeof ServicesCautionAviRoute
  ServicesCommunityManagementRoute: typeof ServicesCommunityManagementRoute
  ServicesCourtSejoursRoute: typeof ServicesCourtSejoursRoute
  ServicesLogementRoute: typeof ServicesLogementRoute
  ServicesLongSejoursRoute: typeof ServicesLongSejoursRoute
  ServicesVisaSchengenRoute: typeof ServicesVisaSchengenRoute
  ServicesVisiteCamerounRoute: typeof ServicesVisiteCamerounRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesFormationsAllemandRoute: typeof ServicesFormationsAllemandRoute
  ServicesFormationsTcfRoute: typeof ServicesFormationsTcfRoute
  ServicesFormationsToeicRoute: typeof ServicesFormationsToeicRoute
  ServicesFormationsIndexRoute: typeof ServicesFormationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/visite-cameroun': {
      id: '/services/visite-cameroun'
      path: '/services/visite-cameroun'
      fullPath: '/services/visite-cameroun'
      preLoaderRoute: typeof ServicesVisiteCamerounRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/visa-schengen': {
      id: '/services/visa-schengen'
      path: '/services/visa-schengen'
      fullPath: '/services/visa-schengen'
      preLoaderRoute: typeof ServicesVisaSchengenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/long-sejours': {
      id: '/services/long-sejours'
      path: '/services/long-sejours'
      fullPath: '/services/long-sejours'
      preLoaderRoute: typeof ServicesLongSejoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/logement': {
      id: '/services/logement'
      path: '/services/logement'
      fullPath: '/services/logement'
      preLoaderRoute: typeof ServicesLogementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/court-sejours': {
      id: '/services/court-sejours'
      path: '/services/court-sejours'
      fullPath: '/services/court-sejours'
      preLoaderRoute: typeof ServicesCourtSejoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/community-management': {
      id: '/services/community-management'
      path: '/services/community-management'
      fullPath: '/services/community-management'
      preLoaderRoute: typeof ServicesCommunityManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/caution-avi': {
      id: '/services/caution-avi'
      path: '/services/caution-avi'
      fullPath: '/services/caution-avi'
      preLoaderRoute: typeof ServicesCautionAviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/billets-avion': {
      id: '/services/billets-avion'
      path: '/services/billets-avion'
      fullPath: '/services/billets-avion'
      preLoaderRoute: typeof ServicesBilletsAvionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/accueil-integration': {
      id: '/services/accueil-integration'
      path: '/services/accueil-integration'
      fullPath: '/services/accueil-integration'
      preLoaderRoute: typeof ServicesAccueilIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$country': {
      id: '/destinations/$country'
      path: '/destinations/$country'
      fullPath: '/destinations/$country'
      preLoaderRoute: typeof DestinationsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new-request': {
      id: '/_authenticated/new-request'
      path: '/new-request'
      fullPath: '/new-request'
      preLoaderRoute: typeof AuthenticatedNewRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/services/formations/': {
      id: '/services/formations/'
      path: '/services/formations'
      fullPath: '/services/formations/'
      preLoaderRoute: typeof ServicesFormationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-requests/': {
      id: '/_authenticated/my-requests/'
      path: '/my-requests'
      fullPath: '/my-requests/'
      preLoaderRoute: typeof AuthenticatedMyRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/services/formations/toeic': {
      id: '/services/formations/toeic'
      path: '/services/formations/toeic'
      fullPath: '/services/formations/toeic'
      preLoaderRoute: typeof ServicesFormationsToeicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/formations/tcf': {
      id: '/services/formations/tcf'
      path: '/services/formations/tcf'
      fullPath: '/services/formations/tcf'
      preLoaderRoute: typeof ServicesFormationsTcfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/formations/allemand': {
      id: '/services/formations/allemand'
      path: '/services/formations/allemand'
      fullPath: '/services/formations/allemand'
      preLoaderRoute: typeof ServicesFormationsAllemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-requests/$id': {
      id: '/_authenticated/my-requests/$id'
      path: '/my-requests/$id'
      fullPath: '/my-requests/$id'
      preLoaderRoute: typeof AuthenticatedMyRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedNewRequestRoute: typeof AuthenticatedNewRequestRoute
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedMyRequestsIdRoute: typeof AuthenticatedMyRequestsIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedMyRequestsIndexRoute: typeof AuthenticatedMyRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedNewRequestRoute: AuthenticatedNewRequestRoute,
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedMyRequestsIdRoute: AuthenticatedMyRequestsIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedMyRequestsIndexRoute: AuthenticatedMyRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  RequestRoute: RequestRoute,
  SearchRoute: SearchRoute,
  DestinationsCountryRoute: DestinationsCountryRoute,
  ServicesAccueilIntegrationRoute: ServicesAccueilIntegrationRoute,
  ServicesBilletsAvionRoute: ServicesBilletsAvionRoute,
  ServicesCautionAviRoute: ServicesCautionAviRoute,
  ServicesCommunityManagementRoute: ServicesCommunityManagementRoute,
  ServicesCourtSejoursRoute: ServicesCourtSejoursRoute,
  ServicesLogementRoute: ServicesLogementRoute,
  ServicesLongSejoursRoute: ServicesLongSejoursRoute,
  ServicesVisaSchengenRoute: ServicesVisaSchengenRoute,
  ServicesVisiteCamerounRoute: ServicesVisiteCamerounRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesFormationsAllemandRoute: ServicesFormationsAllemandRoute,
  ServicesFormationsTcfRoute: ServicesFormationsTcfRoute,
  ServicesFormationsToeicRoute: ServicesFormationsToeicRoute,
  ServicesFormationsIndexRoute: ServicesFormationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
