/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesVisiteAfriqueRouteImport } from './routes/services.visite-afrique'
import { Route as ServicesVisaSchengenRouteImport } from './routes/services.visa-schengen'
import { Route as ServicesTarifsNegociesRouteImport } from './routes/services.tarifs-negocies'
import { Route as ServicesSuiviRecoursRouteImport } from './routes/services.suivi-recours'
import { Route as ServicesSignatureBailRouteImport } from './routes/services.signature-bail'
import { Route as ServicesSeoAdsRouteImport } from './routes/services.seo-ads'
import { Route as ServicesSelectionLogementsRouteImport } from './routes/services.selection-logements'
import { Route as ServicesSafarisExcursionsRouteImport } from './routes/services.safaris-excursions'
import { Route as ServicesReservationsVfsRouteImport } from './routes/services.reservations-vfs'
import { Route as ServicesReseauxSociauxRouteImport } from './routes/services.reseaux-sociaux'
import { Route as ServicesReportingPerformanceRouteImport } from './routes/services.reporting-performance'
import { Route as ServicesRendezVousConsulatRouteImport } from './routes/services.rendez-vous-consulat'
import { Route as ServicesProjetEtudesRouteImport } from './routes/services.projet-etudes'
import { Route as ServicesProgrammeIntegrationRouteImport } from './routes/services.programme-integration'
import { Route as ServicesPlateformesAdmissionRouteImport } from './routes/services.plateformes-admission'
import { Route as ServicesLongSejoursRouteImport } from './routes/services.long-sejours'
import { Route as ServicesLogementRouteImport } from './routes/services.logement'
import { Route as ServicesLettreAcceptationRouteImport } from './routes/services.lettre-acceptation'
import { Route as ServicesIdentiteVisuelleRouteImport } from './routes/services.identite-visuelle'
import { Route as ServicesHotlineContinueRouteImport } from './routes/services.hotline-continue'
import { Route as ServicesGestionBagagesRouteImport } from './routes/services.gestion-bagages'
import { Route as ServicesGastronomieLocaleRouteImport } from './routes/services.gastronomie-locale'
import { Route as ServicesFormulairesPiecesRouteImport } from './routes/services.formulaires-pieces'
import { Route as ServicesEmissionBilletsRouteImport } from './routes/services.emission-billets'
import { Route as ServicesDossierVisaRouteImport } from './routes/services.dossier-visa'
import { Route as ServicesDossierLocataireRouteImport } from './routes/services.dossier-locataire'
import { Route as ServicesCreationSitesWebRouteImport } from './routes/services.creation-sites-web'
import { Route as ServicesCourtSejoursRouteImport } from './routes/services.court-sejours'
import { Route as ServicesCompteBloqueRouteImport } from './routes/services.compte-bloque'
import { Route as ServicesCommunityManagementRouteImport } from './routes/services.community-management'
import { Route as ServicesCircuitsMultiPaysRouteImport } from './routes/services.circuits-multi-pays'
import { Route as ServicesChoixEtablissementsRouteImport } from './routes/services.choix-etablissements'
import { Route as ServicesChauffeurTransfertsRouteImport } from './routes/services.chauffeur-transferts'
import { Route as ServicesCautionAviRouteImport } from './routes/services.caution-avi'
import { Route as ServicesBilletsAvionRouteImport } from './routes/services.billets-avion'
import { Route as ServicesAuditDossierVisaRouteImport } from './routes/services.audit-dossier-visa'
import { Route as ServicesAssuranceVisaRouteImport } from './routes/services.assurance-visa'
import { Route as ServicesAdmissionEtudesRouteImport } from './routes/services.admission-etudes'
import { Route as ServicesAccueilIntegrationRouteImport } from './routes/services.accueil-integration'
import { Route as DestinationsCountryRouteImport } from './routes/destinations.$country'
import { Route as AuthenticatedNewRequestRouteImport } from './routes/_authenticated/new-request'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ServicesFormationsIndexRouteImport } from './routes/services.formations.index'
import { Route as AuthenticatedMyRequestsIndexRouteImport } from './routes/_authenticated/my-requests.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ServicesFormationsToeicRouteImport } from './routes/services.formations.toeic'
import { Route as ServicesFormationsTcfRouteImport } from './routes/services.formations.tcf'
import { Route as ServicesFormationsAllemandRouteImport } from './routes/services.formations.allemand'
import { Route as AuthenticatedMyRequestsIdRouteImport } from './routes/_authenticated/my-requests.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisiteAfriqueRoute = ServicesVisiteAfriqueRouteImport.update({
  id: '/services/visite-afrique',
  path: '/services/visite-afrique',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVisaSchengenRoute = ServicesVisaSchengenRouteImport.update({
  id: '/services/visa-schengen',
  path: '/services/visa-schengen',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTarifsNegociesRoute = ServicesTarifsNegociesRouteImport.update({
  id: '/services/tarifs-negocies',
  path: '/services/tarifs-negocies',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSuiviRecoursRoute = ServicesSuiviRecoursRouteImport.update({
  id: '/services/suivi-recours',
  path: '/services/suivi-recours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSignatureBailRoute = ServicesSignatureBailRouteImport.update({
  id: '/services/signature-bail',
  path: '/services/signature-bail',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeoAdsRoute = ServicesSeoAdsRouteImport.update({
  id: '/services/seo-ads',
  path: '/services/seo-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSelectionLogementsRoute =
  ServicesSelectionLogementsRouteImport.update({
    id: '/services/selection-logements',
    path: '/services/selection-logements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSafarisExcursionsRoute =
  ServicesSafarisExcursionsRouteImport.update({
    id: '/services/safaris-excursions',
    path: '/services/safaris-excursions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesReservationsVfsRoute = ServicesReservationsVfsRouteImport.update({
  id: '/services/reservations-vfs',
  path: '/services/reservations-vfs',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesReseauxSociauxRoute = ServicesReseauxSociauxRouteImport.update({
  id: '/services/reseaux-sociaux',
  path: '/services/reseaux-sociaux',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesReportingPerformanceRoute =
  ServicesReportingPerformanceRouteImport.update({
    id: '/services/reporting-performance',
    path: '/services/reporting-performance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRendezVousConsulatRoute =
  ServicesRendezVousConsulatRouteImport.update({
    id: '/services/rendez-vous-consulat',
    path: '/services/rendez-vous-consulat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesProjetEtudesRoute = ServicesProjetEtudesRouteImport.update({
  id: '/services/projet-etudes',
  path: '/services/projet-etudes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProgrammeIntegrationRoute =
  ServicesProgrammeIntegrationRouteImport.update({
    id: '/services/programme-integration',
    path: '/services/programme-integration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesPlateformesAdmissionRoute =
  ServicesPlateformesAdmissionRouteImport.update({
    id: '/services/plateformes-admission',
    path: '/services/plateformes-admission',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLongSejoursRoute = ServicesLongSejoursRouteImport.update({
  id: '/services/long-sejours',
  path: '/services/long-sejours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLogementRoute = ServicesLogementRouteImport.update({
  id: '/services/logement',
  path: '/services/logement',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLettreAcceptationRoute =
  ServicesLettreAcceptationRouteImport.update({
    id: '/services/lettre-acceptation',
    path: '/services/lettre-acceptation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIdentiteVisuelleRoute =
  ServicesIdentiteVisuelleRouteImport.update({
    id: '/services/identite-visuelle',
    path: '/services/identite-visuelle',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHotlineContinueRoute = ServicesHotlineContinueRouteImport.update({
  id: '/services/hotline-continue',
  path: '/services/hotline-continue',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGestionBagagesRoute = ServicesGestionBagagesRouteImport.update({
  id: '/services/gestion-bagages',
  path: '/services/gestion-bagages',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGastronomieLocaleRoute =
  ServicesGastronomieLocaleRouteImport.update({
    id: '/services/gastronomie-locale',
    path: '/services/gastronomie-locale',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFormulairesPiecesRoute =
  ServicesFormulairesPiecesRouteImport.update({
    id: '/services/formulaires-pieces',
    path: '/services/formulaires-pieces',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEmissionBilletsRoute = ServicesEmissionBilletsRouteImport.update({
  id: '/services/emission-billets',
  path: '/services/emission-billets',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDossierVisaRoute = ServicesDossierVisaRouteImport.update({
  id: '/services/dossier-visa',
  path: '/services/dossier-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDossierLocataireRoute =
  ServicesDossierLocataireRouteImport.update({
    id: '/services/dossier-locataire',
    path: '/services/dossier-locataire',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCreationSitesWebRoute =
  ServicesCreationSitesWebRouteImport.update({
    id: '/services/creation-sites-web',
    path: '/services/creation-sites-web',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCourtSejoursRoute = ServicesCourtSejoursRouteImport.update({
  id: '/services/court-sejours',
  path: '/services/court-sejours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCompteBloqueRoute = ServicesCompteBloqueRouteImport.update({
  id: '/services/compte-bloque',
  path: '/services/compte-bloque',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCommunityManagementRoute =
  ServicesCommunityManagementRouteImport.update({
    id: '/services/community-management',
    path: '/services/community-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCircuitsMultiPaysRoute =
  ServicesCircuitsMultiPaysRouteImport.update({
    id: '/services/circuits-multi-pays',
    path: '/services/circuits-multi-pays',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesChoixEtablissementsRoute =
  ServicesChoixEtablissementsRouteImport.update({
    id: '/services/choix-etablissements',
    path: '/services/choix-etablissements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesChauffeurTransfertsRoute =
  ServicesChauffeurTransfertsRouteImport.update({
    id: '/services/chauffeur-transferts',
    path: '/services/chauffeur-transferts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCautionAviRoute = ServicesCautionAviRouteImport.update({
  id: '/services/caution-avi',
  path: '/services/caution-avi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBilletsAvionRoute = ServicesBilletsAvionRouteImport.update({
  id: '/services/billets-avion',
  path: '/services/billets-avion',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAuditDossierVisaRoute =
  ServicesAuditDossierVisaRouteImport.update({
    id: '/services/audit-dossier-visa',
    path: '/services/audit-dossier-visa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAssuranceVisaRoute = ServicesAssuranceVisaRouteImport.update({
  id: '/services/assurance-visa',
  path: '/services/assurance-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAdmissionEtudesRoute = ServicesAdmissionEtudesRouteImport.update({
  id: '/services/admission-etudes',
  path: '/services/admission-etudes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAccueilIntegrationRoute =
  ServicesAccueilIntegrationRouteImport.update({
    id: '/services/accueil-integration',
    path: '/services/accueil-integration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DestinationsCountryRoute = DestinationsCountryRouteImport.update({
  id: '/destinations/$country',
  path: '/destinations/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewRequestRoute = AuthenticatedNewRequestRouteImport.update({
  id: '/new-request',
  path: '/new-request',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicesFormationsIndexRoute = ServicesFormationsIndexRouteImport.update({
  id: '/services/formations/',
  path: '/services/formations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyRequestsIndexRoute =
  AuthenticatedMyRequestsIndexRouteImport.update({
    id: '/my-requests/',
    path: '/my-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicesFormationsToeicRoute = ServicesFormationsToeicRouteImport.update({
  id: '/services/formations/toeic',
  path: '/services/formations/toeic',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFormationsTcfRoute = ServicesFormationsTcfRouteImport.update({
  id: '/services/formations/tcf',
  path: '/services/formations/tcf',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFormationsAllemandRoute =
  ServicesFormationsAllemandRouteImport.update({
    id: '/services/formations/allemand',
    path: '/services/formations/allemand',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMyRequestsIdRoute =
  AuthenticatedMyRequestsIdRouteImport.update({
    id: '/my-requests/$id',
    path: '/my-requests/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/new-request': typeof AuthenticatedNewRequestRoute
  '/destinations/$country': typeof DestinationsCountryRoute
  '/services/accueil-integration': typeof ServicesAccueilIntegrationRoute
  '/services/admission-etudes': typeof ServicesAdmissionEtudesRoute
  '/services/assurance-visa': typeof ServicesAssuranceVisaRoute
  '/services/audit-dossier-visa': typeof ServicesAuditDossierVisaRoute
  '/services/billets-avion': typeof ServicesBilletsAvionRoute
  '/services/caution-avi': typeof ServicesCautionAviRoute
  '/services/chauffeur-transferts': typeof ServicesChauffeurTransfertsRoute
  '/services/choix-etablissements': typeof ServicesChoixEtablissementsRoute
  '/services/circuits-multi-pays': typeof ServicesCircuitsMultiPaysRoute
  '/services/community-management': typeof ServicesCommunityManagementRoute
  '/services/compte-bloque': typeof ServicesCompteBloqueRoute
  '/services/court-sejours': typeof ServicesCourtSejoursRoute
  '/services/creation-sites-web': typeof ServicesCreationSitesWebRoute
  '/services/dossier-locataire': typeof ServicesDossierLocataireRoute
  '/services/dossier-visa': typeof ServicesDossierVisaRoute
  '/services/emission-billets': typeof ServicesEmissionBilletsRoute
  '/services/formulaires-pieces': typeof ServicesFormulairesPiecesRoute
  '/services/gastronomie-locale': typeof ServicesGastronomieLocaleRoute
  '/services/gestion-bagages': typeof ServicesGestionBagagesRoute
  '/services/hotline-continue': typeof ServicesHotlineContinueRoute
  '/services/identite-visuelle': typeof ServicesIdentiteVisuelleRoute
  '/services/lettre-acceptation': typeof ServicesLettreAcceptationRoute
  '/services/logement': typeof ServicesLogementRoute
  '/services/long-sejours': typeof ServicesLongSejoursRoute
  '/services/plateformes-admission': typeof ServicesPlateformesAdmissionRoute
  '/services/programme-integration': typeof ServicesProgrammeIntegrationRoute
  '/services/projet-etudes': typeof ServicesProjetEtudesRoute
  '/services/rendez-vous-consulat': typeof ServicesRendezVousConsulatRoute
  '/services/reporting-performance': typeof ServicesReportingPerformanceRoute
  '/services/reseaux-sociaux': typeof ServicesReseauxSociauxRoute
  '/services/reservations-vfs': typeof ServicesReservationsVfsRoute
  '/services/safaris-excursions': typeof ServicesSafarisExcursionsRoute
  '/services/selection-logements': typeof ServicesSelectionLogementsRoute
  '/services/seo-ads': typeof ServicesSeoAdsRoute
  '/services/signature-bail': typeof ServicesSignatureBailRoute
  '/services/suivi-recours': typeof ServicesSuiviRecoursRoute
  '/services/tarifs-negocies': typeof ServicesTarifsNegociesRoute
  '/services/visa-schengen': typeof ServicesVisaSchengenRoute
  '/services/visite-afrique': typeof ServicesVisiteAfriqueRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/my-requests/$id': typeof AuthenticatedMyRequestsIdRoute
  '/services/formations/allemand': typeof ServicesFormationsAllemandRoute
  '/services/formations/tcf': typeof ServicesFormationsTcfRoute
  '/services/formations/toeic': typeof ServicesFormationsToeicRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/my-requests/': typeof AuthenticatedMyRequestsIndexRoute
  '/services/formations/': typeof ServicesFormationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/new-request': typeof AuthenticatedNewRequestRoute
  '/destinations/$country': typeof DestinationsCountryRoute
  '/services/accueil-integration': typeof ServicesAccueilIntegrationRoute
  '/services/admission-etudes': typeof ServicesAdmissionEtudesRoute
  '/services/assurance-visa': typeof ServicesAssuranceVisaRoute
  '/services/audit-dossier-visa': typeof ServicesAuditDossierVisaRoute
  '/services/billets-avion': typeof ServicesBilletsAvionRoute
  '/services/caution-avi': typeof ServicesCautionAviRoute
  '/services/chauffeur-transferts': typeof ServicesChauffeurTransfertsRoute
  '/services/choix-etablissements': typeof ServicesChoixEtablissementsRoute
  '/services/circuits-multi-pays': typeof ServicesCircuitsMultiPaysRoute
  '/services/community-management': typeof ServicesCommunityManagementRoute
  '/services/compte-bloque': typeof ServicesCompteBloqueRoute
  '/services/court-sejours': typeof ServicesCourtSejoursRoute
  '/services/creation-sites-web': typeof ServicesCreationSitesWebRoute
  '/services/dossier-locataire': typeof ServicesDossierLocataireRoute
  '/services/dossier-visa': typeof ServicesDossierVisaRoute
  '/services/emission-billets': typeof ServicesEmissionBilletsRoute
  '/services/formulaires-pieces': typeof ServicesFormulairesPiecesRoute
  '/services/gastronomie-locale': typeof ServicesGastronomieLocaleRoute
  '/services/gestion-bagages': typeof ServicesGestionBagagesRoute
  '/services/hotline-continue': typeof ServicesHotlineContinueRoute
  '/services/identite-visuelle': typeof ServicesIdentiteVisuelleRoute
  '/services/lettre-acceptation': typeof ServicesLettreAcceptationRoute
  '/services/logement': typeof ServicesLogementRoute
  '/services/long-sejours': typeof ServicesLongSejoursRoute
  '/services/plateformes-admission': typeof ServicesPlateformesAdmissionRoute
  '/services/programme-integration': typeof ServicesProgrammeIntegrationRoute
  '/services/projet-etudes': typeof ServicesProjetEtudesRoute
  '/services/rendez-vous-consulat': typeof ServicesRendezVousConsulatRoute
  '/services/reporting-performance': typeof ServicesReportingPerformanceRoute
  '/services/reseaux-sociaux': typeof ServicesReseauxSociauxRoute
  '/services/reservations-vfs': typeof ServicesReservationsVfsRoute
  '/services/safaris-excursions': typeof ServicesSafarisExcursionsRoute
  '/services/selection-logements': typeof ServicesSelectionLogementsRoute
  '/services/seo-ads': typeof ServicesSeoAdsRoute
  '/services/signature-bail': typeof ServicesSignatureBailRoute
  '/services/suivi-recours': typeof ServicesSuiviRecoursRoute
  '/services/tarifs-negocies': typeof ServicesTarifsNegociesRoute
  '/services/visa-schengen': typeof ServicesVisaSchengenRoute
  '/services/visite-afrique': typeof ServicesVisiteAfriqueRoute
  '/services': typeof ServicesIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/my-requests/$id': typeof AuthenticatedMyRequestsIdRoute
  '/services/formations/allemand': typeof ServicesFormationsAllemandRoute
  '/services/formations/tcf': typeof ServicesFormationsTcfRoute
  '/services/formations/toeic': typeof ServicesFormationsToeicRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/my-requests': typeof AuthenticatedMyRequestsIndexRoute
  '/services/formations': typeof ServicesFormationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/new-request': typeof AuthenticatedNewRequestRoute
  '/destinations/$country': typeof DestinationsCountryRoute
  '/services/accueil-integration': typeof ServicesAccueilIntegrationRoute
  '/services/admission-etudes': typeof ServicesAdmissionEtudesRoute
  '/services/assurance-visa': typeof ServicesAssuranceVisaRoute
  '/services/audit-dossier-visa': typeof ServicesAuditDossierVisaRoute
  '/services/billets-avion': typeof ServicesBilletsAvionRoute
  '/services/caution-avi': typeof ServicesCautionAviRoute
  '/services/chauffeur-transferts': typeof ServicesChauffeurTransfertsRoute
  '/services/choix-etablissements': typeof ServicesChoixEtablissementsRoute
  '/services/circuits-multi-pays': typeof ServicesCircuitsMultiPaysRoute
  '/services/community-management': typeof ServicesCommunityManagementRoute
  '/services/compte-bloque': typeof ServicesCompteBloqueRoute
  '/services/court-sejours': typeof ServicesCourtSejoursRoute
  '/services/creation-sites-web': typeof ServicesCreationSitesWebRoute
  '/services/dossier-locataire': typeof ServicesDossierLocataireRoute
  '/services/dossier-visa': typeof ServicesDossierVisaRoute
  '/services/emission-billets': typeof ServicesEmissionBilletsRoute
  '/services/formulaires-pieces': typeof ServicesFormulairesPiecesRoute
  '/services/gastronomie-locale': typeof ServicesGastronomieLocaleRoute
  '/services/gestion-bagages': typeof ServicesGestionBagagesRoute
  '/services/hotline-continue': typeof ServicesHotlineContinueRoute
  '/services/identite-visuelle': typeof ServicesIdentiteVisuelleRoute
  '/services/lettre-acceptation': typeof ServicesLettreAcceptationRoute
  '/services/logement': typeof ServicesLogementRoute
  '/services/long-sejours': typeof ServicesLongSejoursRoute
  '/services/plateformes-admission': typeof ServicesPlateformesAdmissionRoute
  '/services/programme-integration': typeof ServicesProgrammeIntegrationRoute
  '/services/projet-etudes': typeof ServicesProjetEtudesRoute
  '/services/rendez-vous-consulat': typeof ServicesRendezVousConsulatRoute
  '/services/reporting-performance': typeof ServicesReportingPerformanceRoute
  '/services/reseaux-sociaux': typeof ServicesReseauxSociauxRoute
  '/services/reservations-vfs': typeof ServicesReservationsVfsRoute
  '/services/safaris-excursions': typeof ServicesSafarisExcursionsRoute
  '/services/selection-logements': typeof ServicesSelectionLogementsRoute
  '/services/seo-ads': typeof ServicesSeoAdsRoute
  '/services/signature-bail': typeof ServicesSignatureBailRoute
  '/services/suivi-recours': typeof ServicesSuiviRecoursRoute
  '/services/tarifs-negocies': typeof ServicesTarifsNegociesRoute
  '/services/visa-schengen': typeof ServicesVisaSchengenRoute
  '/services/visite-afrique': typeof ServicesVisiteAfriqueRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/my-requests/$id': typeof AuthenticatedMyRequestsIdRoute
  '/services/formations/allemand': typeof ServicesFormationsAllemandRoute
  '/services/formations/tcf': typeof ServicesFormationsTcfRoute
  '/services/formations/toeic': typeof ServicesFormationsToeicRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/my-requests/': typeof AuthenticatedMyRequestsIndexRoute
  '/services/formations/': typeof ServicesFormationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/request'
    | '/search'
    | '/account'
    | '/new-request'
    | '/destinations/$country'
    | '/services/accueil-integration'
    | '/services/admission-etudes'
    | '/services/assurance-visa'
    | '/services/audit-dossier-visa'
    | '/services/billets-avion'
    | '/services/caution-avi'
    | '/services/chauffeur-transferts'
    | '/services/choix-etablissements'
    | '/services/circuits-multi-pays'
    | '/services/community-management'
    | '/services/compte-bloque'
    | '/services/court-sejours'
    | '/services/creation-sites-web'
    | '/services/dossier-locataire'
    | '/services/dossier-visa'
    | '/services/emission-billets'
    | '/services/formulaires-pieces'
    | '/services/gastronomie-locale'
    | '/services/gestion-bagages'
    | '/services/hotline-continue'
    | '/services/identite-visuelle'
    | '/services/lettre-acceptation'
    | '/services/logement'
    | '/services/long-sejours'
    | '/services/plateformes-admission'
    | '/services/programme-integration'
    | '/services/projet-etudes'
    | '/services/rendez-vous-consulat'
    | '/services/reporting-performance'
    | '/services/reseaux-sociaux'
    | '/services/reservations-vfs'
    | '/services/safaris-excursions'
    | '/services/selection-logements'
    | '/services/seo-ads'
    | '/services/signature-bail'
    | '/services/suivi-recours'
    | '/services/tarifs-negocies'
    | '/services/visa-schengen'
    | '/services/visite-afrique'
    | '/services/'
    | '/admin/$id'
    | '/admin/users'
    | '/my-requests/$id'
    | '/services/formations/allemand'
    | '/services/formations/tcf'
    | '/services/formations/toeic'
    | '/admin/'
    | '/my-requests/'
    | '/services/formations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/request'
    | '/search'
    | '/account'
    | '/new-request'
    | '/destinations/$country'
    | '/services/accueil-integration'
    | '/services/admission-etudes'
    | '/services/assurance-visa'
    | '/services/audit-dossier-visa'
    | '/services/billets-avion'
    | '/services/caution-avi'
    | '/services/chauffeur-transferts'
    | '/services/choix-etablissements'
    | '/services/circuits-multi-pays'
    | '/services/community-management'
    | '/services/compte-bloque'
    | '/services/court-sejours'
    | '/services/creation-sites-web'
    | '/services/dossier-locataire'
    | '/services/dossier-visa'
    | '/services/emission-billets'
    | '/services/formulaires-pieces'
    | '/services/gastronomie-locale'
    | '/services/gestion-bagages'
    | '/services/hotline-continue'
    | '/services/identite-visuelle'
    | '/services/lettre-acceptation'
    | '/services/logement'
    | '/services/long-sejours'
    | '/services/plateformes-admission'
    | '/services/programme-integration'
    | '/services/projet-etudes'
    | '/services/rendez-vous-consulat'
    | '/services/reporting-performance'
    | '/services/reseaux-sociaux'
    | '/services/reservations-vfs'
    | '/services/safaris-excursions'
    | '/services/selection-logements'
    | '/services/seo-ads'
    | '/services/signature-bail'
    | '/services/suivi-recours'
    | '/services/tarifs-negocies'
    | '/services/visa-schengen'
    | '/services/visite-afrique'
    | '/services'
    | '/admin/$id'
    | '/admin/users'
    | '/my-requests/$id'
    | '/services/formations/allemand'
    | '/services/formations/tcf'
    | '/services/formations/toeic'
    | '/admin'
    | '/my-requests'
    | '/services/formations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/request'
    | '/search'
    | '/_authenticated/account'
    | '/_authenticated/new-request'
    | '/destinations/$country'
    | '/services/accueil-integration'
    | '/services/admission-etudes'
    | '/services/assurance-visa'
    | '/services/audit-dossier-visa'
    | '/services/billets-avion'
    | '/services/caution-avi'
    | '/services/chauffeur-transferts'
    | '/services/choix-etablissements'
    | '/services/circuits-multi-pays'
    | '/services/community-management'
    | '/services/compte-bloque'
    | '/services/court-sejours'
    | '/services/creation-sites-web'
    | '/services/dossier-locataire'
    | '/services/dossier-visa'
    | '/services/emission-billets'
    | '/services/formulaires-pieces'
    | '/services/gastronomie-locale'
    | '/services/gestion-bagages'
    | '/services/hotline-continue'
    | '/services/identite-visuelle'
    | '/services/lettre-acceptation'
    | '/services/logement'
    | '/services/long-sejours'
    | '/services/plateformes-admission'
    | '/services/programme-integration'
    | '/services/projet-etudes'
    | '/services/rendez-vous-consulat'
    | '/services/reporting-performance'
    | '/services/reseaux-sociaux'
    | '/services/reservations-vfs'
    | '/services/safaris-excursions'
    | '/services/selection-logements'
    | '/services/seo-ads'
    | '/services/signature-bail'
    | '/services/suivi-recours'
    | '/services/tarifs-negocies'
    | '/services/visa-schengen'
    | '/services/visite-afrique'
    | '/services/'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/users'
    | '/_authenticated/my-requests/$id'
    | '/services/formations/allemand'
    | '/services/formations/tcf'
    | '/services/formations/toeic'
    | '/_authenticated/admin/'
    | '/_authenticated/my-requests/'
    | '/services/formations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  RequestRoute: typeof RequestRoute
  SearchRoute: typeof SearchRoute
  DestinationsCountryRoute: typeof DestinationsCountryRoute
  ServicesAccueilIntegrationRoute: typeof ServicesAccueilIntegrationRoute
  ServicesAdmissionEtudesRoute: typeof ServicesAdmissionEtudesRoute
  ServicesAssuranceVisaRoute: typeof ServicesAssuranceVisaRoute
  ServicesAuditDossierVisaRoute: typeof ServicesAuditDossierVisaRoute
  ServicesBilletsAvionRoute: typeof ServicesBilletsAvionRoute
  ServicesCautionAviRoute: typeof ServicesCautionAviRoute
  ServicesChauffeurTransfertsRoute: typeof ServicesChauffeurTransfertsRoute
  ServicesChoixEtablissementsRoute: typeof ServicesChoixEtablissementsRoute
  ServicesCircuitsMultiPaysRoute: typeof ServicesCircuitsMultiPaysRoute
  ServicesCommunityManagementRoute: typeof ServicesCommunityManagementRoute
  ServicesCompteBloqueRoute: typeof ServicesCompteBloqueRoute
  ServicesCourtSejoursRoute: typeof ServicesCourtSejoursRoute
  ServicesCreationSitesWebRoute: typeof ServicesCreationSitesWebRoute
  ServicesDossierLocataireRoute: typeof ServicesDossierLocataireRoute
  ServicesDossierVisaRoute: typeof ServicesDossierVisaRoute
  ServicesEmissionBilletsRoute: typeof ServicesEmissionBilletsRoute
  ServicesFormulairesPiecesRoute: typeof ServicesFormulairesPiecesRoute
  ServicesGastronomieLocaleRoute: typeof ServicesGastronomieLocaleRoute
  ServicesGestionBagagesRoute: typeof ServicesGestionBagagesRoute
  ServicesHotlineContinueRoute: typeof ServicesHotlineContinueRoute
  ServicesIdentiteVisuelleRoute: typeof ServicesIdentiteVisuelleRoute
  ServicesLettreAcceptationRoute: typeof ServicesLettreAcceptationRoute
  ServicesLogementRoute: typeof ServicesLogementRoute
  ServicesLongSejoursRoute: typeof ServicesLongSejoursRoute
  ServicesPlateformesAdmissionRoute: typeof ServicesPlateformesAdmissionRoute
  ServicesProgrammeIntegrationRoute: typeof ServicesProgrammeIntegrationRoute
  ServicesProjetEtudesRoute: typeof ServicesProjetEtudesRoute
  ServicesRendezVousConsulatRoute: typeof ServicesRendezVousConsulatRoute
  ServicesReportingPerformanceRoute: typeof ServicesReportingPerformanceRoute
  ServicesReseauxSociauxRoute: typeof ServicesReseauxSociauxRoute
  ServicesReservationsVfsRoute: typeof ServicesReservationsVfsRoute
  ServicesSafarisExcursionsRoute: typeof ServicesSafarisExcursionsRoute
  ServicesSelectionLogementsRoute: typeof ServicesSelectionLogementsRoute
  ServicesSeoAdsRoute: typeof ServicesSeoAdsRoute
  ServicesSignatureBailRoute: typeof ServicesSignatureBailRoute
  ServicesSuiviRecoursRoute: typeof ServicesSuiviRecoursRoute
  ServicesTarifsNegociesRoute: typeof ServicesTarifsNegociesRoute
  ServicesVisaSchengenRoute: typeof ServicesVisaSchengenRoute
  ServicesVisiteAfriqueRoute: typeof ServicesVisiteAfriqueRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesFormationsAllemandRoute: typeof ServicesFormationsAllemandRoute
  ServicesFormationsTcfRoute: typeof ServicesFormationsTcfRoute
  ServicesFormationsToeicRoute: typeof ServicesFormationsToeicRoute
  ServicesFormationsIndexRoute: typeof ServicesFormationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/visite-afrique': {
      id: '/services/visite-afrique'
      path: '/services/visite-afrique'
      fullPath: '/services/visite-afrique'
      preLoaderRoute: typeof ServicesVisiteAfriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/visa-schengen': {
      id: '/services/visa-schengen'
      path: '/services/visa-schengen'
      fullPath: '/services/visa-schengen'
      preLoaderRoute: typeof ServicesVisaSchengenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/tarifs-negocies': {
      id: '/services/tarifs-negocies'
      path: '/services/tarifs-negocies'
      fullPath: '/services/tarifs-negocies'
      preLoaderRoute: typeof ServicesTarifsNegociesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/suivi-recours': {
      id: '/services/suivi-recours'
      path: '/services/suivi-recours'
      fullPath: '/services/suivi-recours'
      preLoaderRoute: typeof ServicesSuiviRecoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/signature-bail': {
      id: '/services/signature-bail'
      path: '/services/signature-bail'
      fullPath: '/services/signature-bail'
      preLoaderRoute: typeof ServicesSignatureBailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo-ads': {
      id: '/services/seo-ads'
      path: '/services/seo-ads'
      fullPath: '/services/seo-ads'
      preLoaderRoute: typeof ServicesSeoAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/selection-logements': {
      id: '/services/selection-logements'
      path: '/services/selection-logements'
      fullPath: '/services/selection-logements'
      preLoaderRoute: typeof ServicesSelectionLogementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/safaris-excursions': {
      id: '/services/safaris-excursions'
      path: '/services/safaris-excursions'
      fullPath: '/services/safaris-excursions'
      preLoaderRoute: typeof ServicesSafarisExcursionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/reservations-vfs': {
      id: '/services/reservations-vfs'
      path: '/services/reservations-vfs'
      fullPath: '/services/reservations-vfs'
      preLoaderRoute: typeof ServicesReservationsVfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/reseaux-sociaux': {
      id: '/services/reseaux-sociaux'
      path: '/services/reseaux-sociaux'
      fullPath: '/services/reseaux-sociaux'
      preLoaderRoute: typeof ServicesReseauxSociauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/reporting-performance': {
      id: '/services/reporting-performance'
      path: '/services/reporting-performance'
      fullPath: '/services/reporting-performance'
      preLoaderRoute: typeof ServicesReportingPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/rendez-vous-consulat': {
      id: '/services/rendez-vous-consulat'
      path: '/services/rendez-vous-consulat'
      fullPath: '/services/rendez-vous-consulat'
      preLoaderRoute: typeof ServicesRendezVousConsulatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/projet-etudes': {
      id: '/services/projet-etudes'
      path: '/services/projet-etudes'
      fullPath: '/services/projet-etudes'
      preLoaderRoute: typeof ServicesProjetEtudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/programme-integration': {
      id: '/services/programme-integration'
      path: '/services/programme-integration'
      fullPath: '/services/programme-integration'
      preLoaderRoute: typeof ServicesProgrammeIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/plateformes-admission': {
      id: '/services/plateformes-admission'
      path: '/services/plateformes-admission'
      fullPath: '/services/plateformes-admission'
      preLoaderRoute: typeof ServicesPlateformesAdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/long-sejours': {
      id: '/services/long-sejours'
      path: '/services/long-sejours'
      fullPath: '/services/long-sejours'
      preLoaderRoute: typeof ServicesLongSejoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/logement': {
      id: '/services/logement'
      path: '/services/logement'
      fullPath: '/services/logement'
      preLoaderRoute: typeof ServicesLogementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lettre-acceptation': {
      id: '/services/lettre-acceptation'
      path: '/services/lettre-acceptation'
      fullPath: '/services/lettre-acceptation'
      preLoaderRoute: typeof ServicesLettreAcceptationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/identite-visuelle': {
      id: '/services/identite-visuelle'
      path: '/services/identite-visuelle'
      fullPath: '/services/identite-visuelle'
      preLoaderRoute: typeof ServicesIdentiteVisuelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hotline-continue': {
      id: '/services/hotline-continue'
      path: '/services/hotline-continue'
      fullPath: '/services/hotline-continue'
      preLoaderRoute: typeof ServicesHotlineContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/gestion-bagages': {
      id: '/services/gestion-bagages'
      path: '/services/gestion-bagages'
      fullPath: '/services/gestion-bagages'
      preLoaderRoute: typeof ServicesGestionBagagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/gastronomie-locale': {
      id: '/services/gastronomie-locale'
      path: '/services/gastronomie-locale'
      fullPath: '/services/gastronomie-locale'
      preLoaderRoute: typeof ServicesGastronomieLocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/formulaires-pieces': {
      id: '/services/formulaires-pieces'
      path: '/services/formulaires-pieces'
      fullPath: '/services/formulaires-pieces'
      preLoaderRoute: typeof ServicesFormulairesPiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/emission-billets': {
      id: '/services/emission-billets'
      path: '/services/emission-billets'
      fullPath: '/services/emission-billets'
      preLoaderRoute: typeof ServicesEmissionBilletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/dossier-visa': {
      id: '/services/dossier-visa'
      path: '/services/dossier-visa'
      fullPath: '/services/dossier-visa'
      preLoaderRoute: typeof ServicesDossierVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/dossier-locataire': {
      id: '/services/dossier-locataire'
      path: '/services/dossier-locataire'
      fullPath: '/services/dossier-locataire'
      preLoaderRoute: typeof ServicesDossierLocataireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/creation-sites-web': {
      id: '/services/creation-sites-web'
      path: '/services/creation-sites-web'
      fullPath: '/services/creation-sites-web'
      preLoaderRoute: typeof ServicesCreationSitesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/court-sejours': {
      id: '/services/court-sejours'
      path: '/services/court-sejours'
      fullPath: '/services/court-sejours'
      preLoaderRoute: typeof ServicesCourtSejoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/compte-bloque': {
      id: '/services/compte-bloque'
      path: '/services/compte-bloque'
      fullPath: '/services/compte-bloque'
      preLoaderRoute: typeof ServicesCompteBloqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/community-management': {
      id: '/services/community-management'
      path: '/services/community-management'
      fullPath: '/services/community-management'
      preLoaderRoute: typeof ServicesCommunityManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/circuits-multi-pays': {
      id: '/services/circuits-multi-pays'
      path: '/services/circuits-multi-pays'
      fullPath: '/services/circuits-multi-pays'
      preLoaderRoute: typeof ServicesCircuitsMultiPaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/choix-etablissements': {
      id: '/services/choix-etablissements'
      path: '/services/choix-etablissements'
      fullPath: '/services/choix-etablissements'
      preLoaderRoute: typeof ServicesChoixEtablissementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/chauffeur-transferts': {
      id: '/services/chauffeur-transferts'
      path: '/services/chauffeur-transferts'
      fullPath: '/services/chauffeur-transferts'
      preLoaderRoute: typeof ServicesChauffeurTransfertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/caution-avi': {
      id: '/services/caution-avi'
      path: '/services/caution-avi'
      fullPath: '/services/caution-avi'
      preLoaderRoute: typeof ServicesCautionAviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/billets-avion': {
      id: '/services/billets-avion'
      path: '/services/billets-avion'
      fullPath: '/services/billets-avion'
      preLoaderRoute: typeof ServicesBilletsAvionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/audit-dossier-visa': {
      id: '/services/audit-dossier-visa'
      path: '/services/audit-dossier-visa'
      fullPath: '/services/audit-dossier-visa'
      preLoaderRoute: typeof ServicesAuditDossierVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/assurance-visa': {
      id: '/services/assurance-visa'
      path: '/services/assurance-visa'
      fullPath: '/services/assurance-visa'
      preLoaderRoute: typeof ServicesAssuranceVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/admission-etudes': {
      id: '/services/admission-etudes'
      path: '/services/admission-etudes'
      fullPath: '/services/admission-etudes'
      preLoaderRoute: typeof ServicesAdmissionEtudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/accueil-integration': {
      id: '/services/accueil-integration'
      path: '/services/accueil-integration'
      fullPath: '/services/accueil-integration'
      preLoaderRoute: typeof ServicesAccueilIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$country': {
      id: '/destinations/$country'
      path: '/destinations/$country'
      fullPath: '/destinations/$country'
      preLoaderRoute: typeof DestinationsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new-request': {
      id: '/_authenticated/new-request'
      path: '/new-request'
      fullPath: '/new-request'
      preLoaderRoute: typeof AuthenticatedNewRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/services/formations/': {
      id: '/services/formations/'
      path: '/services/formations'
      fullPath: '/services/formations/'
      preLoaderRoute: typeof ServicesFormationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-requests/': {
      id: '/_authenticated/my-requests/'
      path: '/my-requests'
      fullPath: '/my-requests/'
      preLoaderRoute: typeof AuthenticatedMyRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/services/formations/toeic': {
      id: '/services/formations/toeic'
      path: '/services/formations/toeic'
      fullPath: '/services/formations/toeic'
      preLoaderRoute: typeof ServicesFormationsToeicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/formations/tcf': {
      id: '/services/formations/tcf'
      path: '/services/formations/tcf'
      fullPath: '/services/formations/tcf'
      preLoaderRoute: typeof ServicesFormationsTcfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/formations/allemand': {
      id: '/services/formations/allemand'
      path: '/services/formations/allemand'
      fullPath: '/services/formations/allemand'
      preLoaderRoute: typeof ServicesFormationsAllemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-requests/$id': {
      id: '/_authenticated/my-requests/$id'
      path: '/my-requests/$id'
      fullPath: '/my-requests/$id'
      preLoaderRoute: typeof AuthenticatedMyRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedNewRequestRoute: typeof AuthenticatedNewRequestRoute
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedMyRequestsIdRoute: typeof AuthenticatedMyRequestsIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedMyRequestsIndexRoute: typeof AuthenticatedMyRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedNewRequestRoute: AuthenticatedNewRequestRoute,
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedMyRequestsIdRoute: AuthenticatedMyRequestsIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedMyRequestsIndexRoute: AuthenticatedMyRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  RequestRoute: RequestRoute,
  SearchRoute: SearchRoute,
  DestinationsCountryRoute: DestinationsCountryRoute,
  ServicesAccueilIntegrationRoute: ServicesAccueilIntegrationRoute,
  ServicesAdmissionEtudesRoute: ServicesAdmissionEtudesRoute,
  ServicesAssuranceVisaRoute: ServicesAssuranceVisaRoute,
  ServicesAuditDossierVisaRoute: ServicesAuditDossierVisaRoute,
  ServicesBilletsAvionRoute: ServicesBilletsAvionRoute,
  ServicesCautionAviRoute: ServicesCautionAviRoute,
  ServicesChauffeurTransfertsRoute: ServicesChauffeurTransfertsRoute,
  ServicesChoixEtablissementsRoute: ServicesChoixEtablissementsRoute,
  ServicesCircuitsMultiPaysRoute: ServicesCircuitsMultiPaysRoute,
  ServicesCommunityManagementRoute: ServicesCommunityManagementRoute,
  ServicesCompteBloqueRoute: ServicesCompteBloqueRoute,
  ServicesCourtSejoursRoute: ServicesCourtSejoursRoute,
  ServicesCreationSitesWebRoute: ServicesCreationSitesWebRoute,
  ServicesDossierLocataireRoute: ServicesDossierLocataireRoute,
  ServicesDossierVisaRoute: ServicesDossierVisaRoute,
  ServicesEmissionBilletsRoute: ServicesEmissionBilletsRoute,
  ServicesFormulairesPiecesRoute: ServicesFormulairesPiecesRoute,
  ServicesGastronomieLocaleRoute: ServicesGastronomieLocaleRoute,
  ServicesGestionBagagesRoute: ServicesGestionBagagesRoute,
  ServicesHotlineContinueRoute: ServicesHotlineContinueRoute,
  ServicesIdentiteVisuelleRoute: ServicesIdentiteVisuelleRoute,
  ServicesLettreAcceptationRoute: ServicesLettreAcceptationRoute,
  ServicesLogementRoute: ServicesLogementRoute,
  ServicesLongSejoursRoute: ServicesLongSejoursRoute,
  ServicesPlateformesAdmissionRoute: ServicesPlateformesAdmissionRoute,
  ServicesProgrammeIntegrationRoute: ServicesProgrammeIntegrationRoute,
  ServicesProjetEtudesRoute: ServicesProjetEtudesRoute,
  ServicesRendezVousConsulatRoute: ServicesRendezVousConsulatRoute,
  ServicesReportingPerformanceRoute: ServicesReportingPerformanceRoute,
  ServicesReseauxSociauxRoute: ServicesReseauxSociauxRoute,
  ServicesReservationsVfsRoute: ServicesReservationsVfsRoute,
  ServicesSafarisExcursionsRoute: ServicesSafarisExcursionsRoute,
  ServicesSelectionLogementsRoute: ServicesSelectionLogementsRoute,
  ServicesSeoAdsRoute: ServicesSeoAdsRoute,
  ServicesSignatureBailRoute: ServicesSignatureBailRoute,
  ServicesSuiviRecoursRoute: ServicesSuiviRecoursRoute,
  ServicesTarifsNegociesRoute: ServicesTarifsNegociesRoute,
  ServicesVisaSchengenRoute: ServicesVisaSchengenRoute,
  ServicesVisiteAfriqueRoute: ServicesVisiteAfriqueRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesFormationsAllemandRoute: ServicesFormationsAllemandRoute,
  ServicesFormationsTcfRoute: ServicesFormationsTcfRoute,
  ServicesFormationsToeicRoute: ServicesFormationsToeicRoute,
  ServicesFormationsIndexRoute: ServicesFormationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
