// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient(): SupabaseClient<Database> {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      "[Supabase] Running in stub mode — no SUPABASE_URL/SUPABASE_PUBLISHABLE_KEY configured. Auth and storage operations will be disabled."
    );
    return createStubClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

function createStubClient(): SupabaseClient<Database> {
  const disabled = (name: string) =>
    Promise.resolve({
      data: null,
      error: new Error(`Supabase is disabled (${name}). Connect Supabase in Lovable Cloud to enable.`),
    });

  return {
    auth: {
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({
        data: { subscription: { unsubscribe: () => {} } },
      }),
      signOut: () => Promise.resolve({ error: null }),
      signUp: () => disabled("signUp"),
      signInWithPassword: () => disabled("signInWithPassword"),
      signInWithOAuth: () => disabled("signInWithOAuth"),
      resetPasswordForEmail: () => disabled("resetPasswordForEmail"),
      updateUser: () => disabled("updateUser"),
      resend: () => disabled("resend"),
    },
    storage: {
      from: () => ({
        uploadToSignedUrl: () => disabled("uploadToSignedUrl"),
        createSignedUrl: () => disabled("createSignedUrl"),
        createSignedUploadUrl: () => disabled("createSignedUploadUrl"),
      }),
    },
  } as unknown as SupabaseClient<Database>;
}

let _supabase: SupabaseClient<Database> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
